### ISSUE TITLE
Bug: fail to add shadcn accordion

### ISSUE THREAD

**Issue by pruge** [MaximePremont/boilerplate-nextron-shadcn#65]
### Contact Details

strive1024@gmail.com

### What happened ?

The shadcn button is installed well.
```
npx shadcn@latest add button
```
```
✔ Checking registry.
✔ Installing dependencies.
✔ Created 1 file:
  - renderer/components/ui/button.tsx
```

But the accordion is not installed.
```
npx shadcn@latest add accordion
```
```
✔ Checking registry.
⠋ Updating @/tailwind.config.js
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

ENOENT: no such file or directory, open '/Volumes/.../project/@/tailwind.config.js'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MaximePremont** [comment]
Hello, fthank you for your report !
There is actually a problem with the `components.json` file of shadcn/ui. I'm just waiting for the fix and I update the project.

**Comment by MaximePremont** [comment]
Hello @pruge , thanks again for your report.
The problem is fixed and released ( https://github.com/MaximePremont/boilerplate-nextron-shadcn/releases/tag/v1.1.1 )
